version: '2'

services:
 db:
  image: microsoft/mssql-server-2016-express-windows
  volumes:
   - .\data:C:\Data 
  environment:
   sa_password: Sitecore+Docker=Socker!
   attach_dbs: "[{'dbName':'Sitecore_Core','dbFiles':['C:\\\\Data\\\\Sitecore.Core.mdf','C:\\\\Data\\\\Sitecore.Core.ldf']},{'dbName':'Sitecore_Master','dbFiles':['C:\\\\Data\\\\Sitecore.Master.mdf', 'C:\\\\Data\\\\Sitecore.Master.ldf']},{'dbName': 'Sitecore_Web', 'dbFiles': ['C:\\\\Data\\\\Sitecore.Web.mdf','C:\\\\Data\\\\Sitecore.Web.ldf']},{'dbName':'Sitecore_Analytics','dbFiles':['C:\\\\Data\\\\Sitecore.Analytics.mdf','C:\\\\Data\\\\Sitecore.Analytics.ldf']}]"   
  mem_limit: 1024m

 web:
  build: .\docker\web
  volumes:
   - .\src\WebApp:C:\Workspace
  links: 
   - db
  environment:
   sa_password: Sitecore+Docker=Socker!
   sql_server: db
  mem_limit: 1024m

networks:
 default:
  external:
   name: "nat"